name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  animated_text_kit: ^2.3.0
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^4.0.1
  path_provider: ^1.6.24
  image_picker: ^0.6.7+12
  modal_progress_hud: ^0.1.3
  true_time: ^0.1.0
  intl: ^0.16.1
  extended_image: ^1.3.0
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
